# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# tasks:
#  - name: Install dependencies and start dev env
#    init: yarn
#    command: yarn serve

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080 # will be used by 'yarn dev'
    onOpen: open-preview
  - port: 4000

vscode:
  extensions:
    - octref.vetur
